# Generated by Django 3.0.4 on 2020-03-24 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('condition', models.CharField(max_length=4)),
                ('body_style', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('interior_color', models.CharField(max_length=10)),
                ('drivetrain', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=10)),
                ('mileage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advisors.Advisor')),
            ],
        ),
    ]
